version: "3.9"
services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    container_name: homelister-web
    depends_on:
      - server
    ports:
      - "3000:3000"
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    container_name: homelister-api
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    # platform: linux/x86_64 # needed for M1/Apple Silicon
    image: mongo:4.2.2
    container_name: homelister-db
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
